=== AnarManafov/PoD/PROOFAgent/documentation/PROOFAgent_config/proofagent.cfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="proofagent_config">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="instances"/>
			</xsd:sequence>
			<xsd:attribute name="last_update" type="xsd:date" use="required"/>
			<xsd:attribute name="version" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="instances">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="instance"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="instance">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="config"/>
				<xsd:choice maxOccurs="1" minOccurs="1">
					<xsd:element ref="agent_server"/>
					<xsd:element ref="agent_client"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="type" type="instanceType"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="instanceType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="server"/>
			<xsd:enumeration value="client"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="config">
		<xsd:complexType mixed="true">
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="work_dir" type="xsd:string"/>
				<xsd:element name="logfile_dir" type="xsd:string"/>
				<xsd:element name="logfile_overwrite" type="xsd:boolean"/>
				<xsd:element name="log_level" type="xsd:nonNegativeInteger"/>
				<xsd:element name="timeout" type="xsd:nonNegativeInteger"/>
				<xsd:element name="proof_cfg_path" type="xsd:string"/>
				<xsd:element name="last_execute_cmd" type="xsd:string"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="agent_server">
		<xsd:complexType mixed="true">
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="listen_port" type="xsd:nonNegativeInteger"/>
				<xsd:element name="local_client_port_min" type="xsd:nonNegativeInteger"/>
				<xsd:element name="local_client_port_max" type="xsd:nonNegativeInteger"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="agent_client">
		<xsd:complexType mixed="true">
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="server_port" type="xsd:nonNegativeInteger"/>
				<xsd:element name="server_addr" type="xsd:string"/>
				<xsd:element name="local_proofd_port" type="xsd:nonNegativeInteger"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== AnarManafov/PoD/gLitePROOF/proofagent.cfg.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<proofagent_config last_update="2008-01-15" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www-linux.gsi.de/~manafov/D-Grid/docz/proofagent.cfg.xsd">
	<instances>
		<instance name="server" type="server">
			<config>
				<work_dir>/tmp/</work_dir>
				<logfile_dir>/tmp/</logfile_dir>
				<logfile_overwrite>true</logfile_overwrite>
				<log_level>0</log_level>
				<timeout>0</timeout>
				<proof_cfg_path>~/proof.conf</proof_cfg_path>
				<last_execute_cmd/>
			</config>
			<agent_server>
				<listen_port>21111</listen_port>
				<local_client_port_min>20000</local_client_port_min>
				<local_client_port_max>25000</local_client_port_max>
			</agent_server>
		</instance>
		<instance name="client" type="client">
			<config>
				<work_dir>/tmp/</work_dir>
				<logfile_dir>_G_WRK_DIR</logfile_dir>
				<logfile_overwrite>true</logfile_overwrite>
				<log_level>0</log_level>
				<timeout>0</timeout>
				<proof_cfg_path>_G_WRK_DIR/proof.conf</proof_cfg_path>
				<last_execute_cmd/>
			</config>
			<agent_client>
				<server_port>21111</server_port>
				<server_addr>depc218.gsi.de</server_addr>
				<local_proofd_port>1093</local_proofd_port>
			</agent_client>
		</instance>
	</instances>
</proofagent_config>

=== AnarManafov/PoD/documentation/PROOFAgent_config/proofagent.cfg.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<proofagent_config last_update="2008-01-15" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www-linux.gsi.de/~manafov/D-Grid/docz/proofagent.cfg.xsd">
	<instances>
		<instance name="server0" type="server">
			<config>
				<work_dir>/tmp/</work_dir>
				<logfile_dir>/tmp/</logfile_dir>
				<logfile_overwrite>true</logfile_overwrite>
				<log_level>0</log_level>
				<timeout>0</timeout>
				<proof_cfg_path>~/proof.conf.server</proof_cfg_path>
				<last_execute_cmd/>
			</config>
			<agent_server>
				<listen_port>51510</listen_port>
				<local_client_port_min>20000</local_client_port_min>
				<local_client_port_max>20010</local_client_port_max>
			</agent_server>
		</instance>
		<instance name="client0" type="client">
			<config>
				<work_dir>/tmp/</work_dir>
				<logfile_dir>/tmp/</logfile_dir>
				<logfile_overwrite>true</logfile_overwrite>
				<log_level>0</log_level>
				<timeout>0</timeout>
				<proof_cfg_path>~/proof.conf.server</proof_cfg_path>
				<last_execute_cmd/>
			</config>
			<agent_client>
				<server_port>51510</server_port>
				<server_addr>127.0.0.1</server_addr>
				<local_proofd_port>1093</local_proofd_port>
			</agent_client>
		</instance>
		<instance name="client1" type="client">
			<config>
				<work_dir>/tmp/</work_dir>
				<logfile_dir>/tmp/</logfile_dir>
				<logfile_overwrite>true</logfile_overwrite>
				<log_level>0</log_level>
				<timeout>0</timeout>
				<proof_cfg_path>~/proof.conf.server</proof_cfg_path>
				<last_execute_cmd/>
			</config>
			<agent_client>
				<server_port>51510</server_port>
				<server_addr>127.0.0.1</server_addr>
				<local_proofd_port>1093</local_proofd_port>
			</agent_client>
		</instance>
	</instances>
</proofagent_config>
